app/restaurants/forms.py
from flask.ext.wtf import Form, RadioField, TextField, Required, TextArea, \
  Length, FloatField, QuerySelectMultipleField, Select, NumberRange, \
  HiddenInput, QuerySelectField, ValidationError, BooleanField, \
  SelectField, DateTimeField

from app.recipes.models import get_ingredients, get_recipes
from app.images.models import get_images
from app.recipes.constants import CATEGORIES
from app.lib.widgets import auto_complete, Button, image_picker
from app.lib.fields import ListTextField
from app.lib.validators import OptionalIf

import constants as RESTAURANT
from .models import Dish, Menu, MenuDish, Place, get_dishes, get_places


class RestaurantForm(Form):
  category_id = RadioField("Category", choices=RESTAURANT.CATEGORIES,
    coerce=int, widget=Select())
  name = TextField("Restaurant's name", [Required(), Length(min=3, max=255)])


class PlaceForm(Form):
  name = TextField("Name", [Required(), Length(max=255)])
  street = TextField("Street", [Required(), Length(max=1024)])
  zipcode = TextField("Zipcode", [Required(), Length(max=32)])
  city = TextField("City", [Required(), Length(max=255)])
  state = TextField("State", [Required(), Length(max=2)])
  blah = TextField("City",widget=HiddenInput)
  longitude = FloatField(validators=[Required(), NumberRange(min=-180, max=180)])
  latitude = FloatField(validators=[Required(), NumberRange(min=-90, max=90)])

  def __init__(self, *args, **kwargs):
    super(PlaceForm, self).__init__(*args, **kwargs)
    self.place = kwargs.get("obj")
    self.restaurant_id = self.place and self.place.restaurant_id or \
      kwargs.pop("restaurant_id")

  def validate_name(self, field):
    if self.place and self.place.name == field.data:
      return

    if Place.query.filter_by(name=field.data,
                            restaurant_id=self.restaurant_id).all():
      raise ValidationError("Place \"%s\" already exist." % field.data)


class MenuForm(Form):
  name = TextField("Name", [Required(), Length(max=255)])
  monday = BooleanField(widget=Button())
  tuesday = BooleanField("Tuesday", widget=Button())
  wednesday = BooleanField("Wednesday", widget=Button())
  thursday = BooleanField("Thursday", widget=Button())
  friday = BooleanField("Friday", widget=Button())
  saturday = BooleanField("Saturday", widget=Button())
  sunday = BooleanField("Sunday", widget=Button())
  start = DateTimeField("Starts", format="%H:%M")
  stop = DateTimeField("Stops", format="%H:%M")
  places = QuerySelectMultipleField(u"Serving places", get_label="name",
    allow_blank=True, query_factory=get_places, widget=auto_complete)

  def __init__(self, *args, **kwargs):
    super(MenuForm, self).__init__(*args, **kwargs)
    self.menu = kwargs.get("obj")
    self.restaurant_id = self.menu and self.menu.restaurant_id or \
      kwargs.pop("restaurant_id")

  def validate_name(self, field):
    if self.menu and self.menu.name == field.data:
      return

    if Menu.query.filter_by(name=field.data,
                            restaurant_id=self.restaurant_id).all():
      raise ValidationError("Menu \"%s\" already exist." % field.data)


class MenuDishForm(Form):
  price = FloatField("Price", [Required(), NumberRange(min=0)])
  name = TextField("Name", [Required(), Length(max=255)])
  category = SelectField(choices=CATEGORIES, coerce=int)
  description = TextField("Description", widget=TextArea())
  dishes = QuerySelectMultipleField("Dishes", [Required()], get_label="name",
    allow_blank=True, query_factory=get_dishes, widget=auto_complete)

  def __init__(self, *args, **kwargs):
    super(MenuDishForm, self).__init__(*args, **kwargs)
    self.menu_dish = kwargs.get("obj")
    self.menu_id = self.menu_dish and self.menu_dish.menu_id or kwargs.pop("menu_id")

  def validate_name(self, field):
    if self.menu_dish and self.menu_dish.name == field.data:
      return

    if MenuDish.query.filter_by(name=field.data, menu_id=self.menu_id).all():
      raise ValidationError("\"%s\" already exists in this menu." % field.data)

class DishForm(Form):
  name = TextField("Name", [Required(), Length(max=255)])

  def __init__(self, *args, **kwargs):
    super(DishForm, self).__init__(*args, **kwargs)
    self.dish = kwargs.get("obj")
    self.restaurant_id = self.dish and self.dish.restaurant_id or kwargs.pop("restaurant_id")

  def validate_name(self, field):
    if self.dish and self.dish.name == field.data:
      return

    if Dish.query.filter_by(name=field.data,
                            restaurant_id=self.restaurant_id).all():
      raise ValidationError("Dish \"%s\" already exist." % field.data)


class FullDishForm(DishForm):
  category_id = SelectField(choices=CATEGORIES, coerce=int)
  ingredients = QuerySelectMultipleField("Ingredients", [Required()],
    get_label="name", allow_blank=True, query_factory=get_ingredients,
    widget=auto_complete)
  hero_ingredient = QuerySelectField("Hero Ingredient", [Required()],
    get_label="name", allow_blank=True, query_factory=get_ingredients,
    widget=auto_complete)
  recipe = QuerySelectField("Recipe",  [OptionalIf('recipe_suggest')],
    get_label="name", allow_blank=True, query_factory=get_recipes,
    widget=auto_complete)
  description = TextField("Description", widget=TextArea())
  image = QuerySelectField("Update Image", get_label="file",
    allow_blank=True, query_factory=get_images, widget=image_picker)
  ingredients_suggest = ListTextField()
  recipe_suggest = TextField()


class RestaurantPostCommentForm(Form):
  content = TextField("Content", widget=TextArea())


class RestaurantPostForm(Form):
  content = TextField("Content", widget=TextArea())
  image = QuerySelectField("Add an Image", get_label="file",
    allow_blank=True, query_factory=get_images, widget=image_picker)

app/restaurants/views.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask.ext.login import login_required, current_user

from app import db
from app.lib.decorators import remote
from app.recipes.views import suggested_ingredient, suggested_recipe

from .forms import RestaurantForm, MenuForm, DishForm, PlaceForm, MenuDishForm,\
  FullDishForm, RestaurantPostForm, RestaurantPostCommentForm
from .models import Restaurant, Menu, Role, Dish, Place, MenuDish, \
  RestaurantPost, RestaurantPostComment
from .constants import OWNER, RESTAURANT


mod = Blueprint("restaurants", __name__, url_prefix="/restaurants")


def _create_restaurant(name, user, category_id=RESTAURANT):
  restaurant = Restaurant()
  restaurant.name = name
  restaurant.category_id = category_id
  db.session.add(restaurant)

  restaurant_user = Role()
  restaurant_user.restaurant = restaurant
  restaurant_user.user = user
  restaurant_user.role_id = OWNER
  db.session.add(restaurant_user)
  return restaurant


@mod.route("/<int:id>/post/", methods=["POST"])
@login_required
def create_post(id):
  restaurant = Restaurant.query.get_or_404(id)
  form = RestaurantPostForm()
  if form.validate_on_submit():
    post = RestaurantPost()
    post.restaurant = restaurant
    post.author = current_user.user
    post.content = form.content.data
    post.image = form.image.data
    db.session.add(post)
    db.session.commit()
    flash('Your post has been created', 'success')
  else:
    flash('An error occured during the creation of your post', 'error')

  return redirect(url_for("restaurants.view_restaurant", id=restaurant.id))


@mod.route("/<int:id>/post_comment/", methods=["POST"])
@login_required
def create_post_comment(id):
  post = RestaurantPost.query.get_or_404(id)
  form = RestaurantPostCommentForm()
  hashtag = ""
  if form.validate_on_submit():
    comment = RestaurantPostComment()
    comment.post = post
    comment.author = current_user.user
    comment.content = form.content.data
    db.session.add(comment)
    db.session.commit()
    flash('Your comment has been created', 'success')
    hashtag = "#comment_%s" % comment.id

  else:
    flash('An error occured during the creation of your comment', 'error')

  return redirect(
    url_for("restaurants.view_restaurant", id=post.restaurant.id) + hashtag)


@mod.route("/<int:id>/", methods=["GET"])
def view_restaurant(id):
  """
  public facing restaurant page
  """
  restaurant = Restaurant.query.get_or_404(id)
  kwargs = {
    "restaurant": restaurant,
    "posts": restaurant.posts[:10],
  }

  if current_user.is_authenticated():
    kwargs["post_form"] = RestaurantPostForm()
    kwargs["comment_form"] = RestaurantPostCommentForm()

  return render_template("restaurants/restaurant.html", **kwargs)


# first url only present to resolve purpose
@mod.route("/r/comments/", methods=["GET"])
@mod.route("/r/comments/<int:id>/", methods=["GET"])
def post_comments(id=0):
  """
  loads all the comments minus the last 2 ones for a given post
  """
  post = RestaurantPost.query.get_or_404(id)

  return render_template("restaurants/restaurant_comments.html",
    comments=reversed(post.comments[2:]))


@mod.route("/r/<int:id>/", methods=["GET"])
@mod.route("/r/<int:id>/<int:page>/", methods=["GET"])
def more_posts(id, page=1):
  """
  loads another set of post
  """
  restaurant = Restaurant.query.get_or_404(id)
  kwargs = {
    'posts': restaurant.posts.paginate(page, per_page=2)
  }

  if current_user.is_authenticated():
    kwargs["comment_form"] = RestaurantPostCommentForm()

  return render_template("restaurants/restaurant_posts.html", **kwargs)


@mod.route("/<int:id>/edit/", methods=["GET", "POST"])
@login_required
def edit_restaurant(id):
  """
  restaurant edit form
  """
  role = current_user.user.roles.\
    filter_by(role_id=OWNER, restaurant_id=id).first_or_404()
  restaurant = role.restaurant

  form = RestaurantForm(request.form, obj=restaurant)
  if form.validate_on_submit():
    restaurant.category_id = form.category_id.data
    restaurant.name = form.name.data
    db.session.commit()
    return redirect(url_for("restaurants.settings", id=restaurant.id))
  return render_template("restaurants/edit_restaurant.html", form=form,
    restaurant=restaurant)


@mod.route("/create/", methods=["GET", "POST"])
@login_required
def create_restaurant():
  """
  restaurant create form
  """
  form = RestaurantForm(request.form)
  if form.validate_on_submit():
    restaurant = _create_restaurant(
      name=form.name.data,
      user=current_user.user,
      category_id=form.category_id.data
    )
    db.session.add(restaurant)
    db.session.commit()
    return redirect(url_for("restaurants.settings", id=restaurant.id))
  return render_template("restaurants/create_restaurant.html", form=form)


@mod.route("/edit/place/<int:id>/", methods=["GET", "POST"])
@login_required
def edit_place(id):
  """
  Edit a place to be linked to the restaurant
  """
  place = Place.query.filter_by(id=id).first_or_404()

  role = current_user.user.roles.\
    filter_by(role_id=OWNER, restaurant_id=place.restaurant_id).first_or_404()
  restaurant = role.restaurant

  form = PlaceForm(obj=place)
  if form.validate_on_submit():
    place.name = form.name.data
    place.street = form.street.data
    place.city = form.city.data
    place.zipcode = form.zipcode.data
    place.state = form.state.data
    place.longitude = form.longitude.data
    place.latitude = form.latitude.data
    db.session.commit()
    flash("Place successfully saved", "success")
    return redirect(url_for("restaurants.settings", id=restaurant.id))

  return render_template("restaurants/edit_place.html", form=form,
    section="restaurant_%s" % restaurant.id, restaurant=restaurant)


@mod.route("/<int:id>/create/place/", methods=["GET", "POST"])
@login_required
def create_place(id):
  """
  Create a place to be linked to the restaurant
  """
  role = current_user.user.roles.\
    filter_by(role_id=OWNER, restaurant_id=id).first_or_404()
  restaurant = role.restaurant

  form = PlaceForm(restaurant_id=restaurant.id)
  if form.validate_on_submit():
    place = Place()
    place.name = form.name.data
    place.street = form.street.data
    place.city = form.city.data
    place.zipcode = form.zipcode.data
    place.state = form.state.data
    place.longitude = form.longitude.data
    place.latitude = form.latitude.data
    place.restaurant = restaurant
    db.session.add(place)
    db.session.commit()
    flash("Place successfully created", "success")
    return redirect(url_for("restaurants.settings", id=restaurant.id))

  return render_template("restaurants/create_place.html", form=form,
    section="restaurant_%s" % restaurant.id, restaurant=restaurant)


@mod.route("/<int:id>/create/menu/", methods=["GET", "POST"])
@login_required
def create_menu(id):
  """
  Create a menu to be linked to the restaurant
  id = restaurant id where the menu is available
  """
  role = current_user.user.roles.\
    filter_by(role_id=OWNER, restaurant_id=id).first_or_404()
  restaurant = role.restaurant

  form = MenuForm(restaurant_id=restaurant.id)
  if form.validate_on_submit():
    menu = Menu()
    menu.name = form.name.data
    menu.restaurant = restaurant
    db.session.add(menu)
    db.session.commit()
    flash("Menu successfully created", "success")
    return redirect(url_for("restaurants.edit_menu", id=menu.id))

  return render_template("restaurants/create_menu.html", form=form,
    restaurant=restaurant)


@mod.route("/menu/<int:id>/edit/", methods=["GET", "POST"])
@login_required
def edit_menu(id):
  """
  Edit a menu
  """
  menu = Menu.query.get_or_404(id)

  role = current_user.user.roles.\
    filter_by(role_id=OWNER, restaurant_id=menu.restaurant.id).first_or_404()
  restaurant = role.restaurant

  form = MenuForm(request.form, obj=menu)
  if form.validate_on_submit():
    menu.name = form.name.data
    menu.places = form.places.data
    menu.monday = form.monday.data
    menu.tuesday = form.tuesday.data
    menu.wednesday = form.wednesday.data
    menu.thursday = form.thursday.data
    menu.friday = form.friday.data
    menu.saturday = form.saturday.data
    menu.sunday = form.sunday.data
    menu.start = form.start.data.time()
    menu.stop = form.stop.data.time()
    db.session.commit()
    flash("Menu successfully saved.", "success")
    return redirect(url_for("restaurants.settings", id=restaurant.id))

  return render_template("restaurants/edit_menu.html", form=form,
    menu=menu, restaurant=restaurant,
    menu_dish_form=MenuDishForm(prefix="md_", menu_id=menu.id))


@mod.route("/menu/dish/delete/<int:id>/", methods=["POST"])
@login_required
def delete_menu_dish(id):
  menu_dish = MenuDish.query.get(id)

  current_user.user.roles.filter_by(restaurant_id=menu_dish.menu.restaurant_id,
                                    role_id=OWNER).first_or_404()

  db.session.delete(menu_dish)
  db.session.commit();
  flash("Dish %s has been removed from this menu." % menu_dish.name, "success")
  return redirect(url_for("restaurants.edit_menu", id=menu_dish.menu_id))


@mod.route("/dish/<int:id>/edit/", methods=["GET", "POST"])
@login_required
def edit_dish(id):
  """
  Edit a dish
  """
  dish = Dish.query.get_or_404(id)

  role = current_user.user.roles.\
    filter_by(role_id=OWNER, restaurant_id=dish.restaurant_id).first_or_404()
  restaurant = role.restaurant

  form = FullDishForm(request.form, obj=dish)
  if form.validate_on_submit():
    dish.name = form.name.data
    dish.description = form.description.data
    dish.category_id = form.category_id.data
    dish.hero_ingredient = form.hero_ingredient.data
    dish.ingredients = form.ingredients.data

    for ingredient in form.ingredients_suggest.data:
      ingredient = suggested_ingredient(ingredient)
      if ingredient:
        dish.ingredients.append(ingredient)

    if form.recipe_suggest.data:
      dish.recipe = suggested_recipe(form.recipe_suggest.data,

app/templates/restaurants/create_dish.html
{% extends "base.html" %}

{% from "lib/forms.html" import render_field %}
{% from "lib/navigation.html" import breadcrumbs %}

{% block content %}
  {{ breadcrumbs('Create a dish',
    (url_for('identities.settings'), 'Settings'),
    (url_for('restaurants.settings', id=restaurant.id), restaurant.name),
  ) }}
  <legend id="profile">Create a dish</legend>
  <form method="post" class="form-horizontal">
    {{ form.hidden_tag() }}
    {{ render_field(form.name) }}
    <div class="form-actions">
      <button type="submit" id="save_btn" class="btn btn-success">
        <i class="icon-ok icon-white"></i> Create dish
      </button>
      <a class="btn" href="{{ url_for('restaurants.settings', id=restaurant.id) }}">
        Cancel
      </a>
    </div>
  </form>
{% endblock %}

{% block footerscript %}
  document.getElementById('name').focus();
{% endblock %}

app/templates/restaurants/create_menu.html
{% extends "base.html" %}

{% from "lib/forms.html" import render_field %}
{% from "lib/navigation.html" import breadcrumbs %}

{% block content %}
  {{ breadcrumbs('Create a menu',
    (url_for('identities.settings'), 'Settings'),
    (url_for('restaurants.settings', id=restaurant.id), restaurant.name),
  ) }}
  <legend id="profile">Create a menu</legend>
  <form method="post" class="form-horizontal">
    {{ form.hidden_tag() }}
    {{ render_field(form.name, class="input text") }}
    <div class="form-actions">
      <button type="submit" id="save_btn" class="btn btn-success">
        <i class="icon-ok icon-white"></i> Create menu
      </button>
      <a class="btn" href="{{ url_for('restaurants.settings', id=restaurant.id) }}">
        Cancel
      </a>
    </div>
  </form>
{% endblock %}

app/templates/restaurants/create_place.html
{% extends "base.html" %}

{% from "lib/forms.html" import render_field %}
{% from "lib/navigation.html" import breadcrumbs %}

{% block content %}
  {{ breadcrumbs('Create a place',
    (url_for('identities.settings'), 'Settings'),
    (url_for('restaurants.settings', id=restaurant.id), restaurant.name),
  ) }}
  <div class="row">
    <div class="span6">
      <legend id="profile">Create a place</legend>
      <form method="post" class="form-horizontal" id="address_form">
        {{ form.hidden_tag() }}
        {{ render_field(form.name) }}
        {{ render_field(form.street) }}
        {{ render_field(form.zipcode) }}
        {{ render_field(form.city) }}
        {{ render_field(form.state) }}
        {{ form.latitude(type="hidden") }}
        {{ form.longitude(type="hidden") }}
        <div class="form-actions">
          <a id="check_btn" class="btn btn-primary">
            <i class="icon-ok icon-white"></i> Check on the map
          </a>
          <button type="submit" id="save_btn" class="btn btn-success hidden">
            <i class="icon-ok icon-white"></i> The map is correct, save place.
          </button>
          <a class="btn" href="{{ url_for("restaurants.settings", id=restaurant.id) }}">
            Cancel
          </a>
        </div>
      </form>
    </div>
    <div class="span6">
      <div id="map_canvas">
        <div class="loading_map">
          Enter your address and confirm it on the map here.
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block headscript %}
  $script("{{ url_for("static", filename="lib/openlayer212/OpenLayers.js") }}", 'openlayer');
  $script("{{ url_for("static", filename="js/map.js") }}");
  var map;
{% endblock %}

{% block jquery %}
  $('#check_btn').on('click', code_form_address);
  function code_form_address(){
    var query = {
      street: $("#street").val(),
      city: $("#city").val(),
      state: $("#state").val(),
      country: 'USA',
      postalcode: $("#zipcode").val(),
      format: 'json'
    };
    if (!(query.street && query.city && query.state && query.postalcode)){
      alert('Address is incomplete')
      return;
    }
    if (!map){
      map = new CA.map({div: 'map_canvas'});
    }
    map.geocode(query, function(data){
      if (data.length){
        $('#check_btn').addClass('hidden');
        $('#save_btn').removeClass('hidden');
        $('#latitude').val(data[0].lat);
        $('#longitude').val(data[0].lon);
        map.clear_markers();
        map.marker(data[0].lon, data[0].lat);
        map.center(data[0].lon, data[0].lat, 15);
      }else{
        $('#check_btn').removeClass('hidden');
        $('#save_btn').addClass('hidden');
        alert("The address you specified cannot be found.")
      }
    });
  }

  $("#address_form .controls > input").change(function(){
    $("#check_btn").removeClass("hidden");
    $("#save_btn").addClass("hidden");
  });
{% endblock %}

app/templates/restaurants/create_restaurant.html
{% extends "base.html" %}

{% from "lib/forms.html" import render_field %}

{% block content %}
  <legend>Create a restaurant</legend>
  <form method="POST" action="" class="form-horizontal">
    {{ form.hidden_tag() }}
    {{ render_field(form.name) }}
    {{ render_field(form.category_id) }}
    <p class="alert alert-info">
      By clicking Create, you agree to our
      <a href="/about/tos/"><strong>terms of service</strong></a>.
    </p>
    <div class="form-actions">
      <button type="submit" class="btn btn-success">
        <i class="icon-ok icon-white"></i> Create Restaurant
      </button>
      <a class="btn" href="{{ url_for("identities.settings") }}">
        Cancel
      </a>
    </div>
  </form>
{% endblock %}

app/templates/restaurants/edit_restaurant.html
{% extends "base.html" %}

{% from "lib/forms.html" import render_field %}

{% block content %}
  <legend>Update "{{ restaurant.name|e }}"</legend>
  <form method="POST" action="" class="form-horizontal">
    {{ form.hidden_tag() }}
    {{ render_field(form.name) }}
    {{ render_field(form.category_id) }}
    <div class="form-actions">
      <button type="submit" class="btn btn-success">
        <i class="icon-ok icon-white"></i> Update Restaurant
      </button>
      <a class="btn" href="{{ url_for("identities.settings") }}">
        Cancel
      </a>
    </div>
  </form>
{% endblock %}

app/templates/restaurants/restaurant.html
{% extends "base.html" %}

{% from "lib/forms.html" import render_field %}
{% from "restaurants/macros/post.html" import render_post %}

{% block css %}
  {{ super() }}
  <link rel="stylesheet" href="{{url_for("static",
    filename="lib/jcrop/jquery.Jcrop.min.css") }}">
{% endblock %}

{% block content %}
  <div class="row">
    <div class="span3">
    </div>
    <div class="span6">
      <h2>{{ restaurant.name }}</h2>
      {% if post_form %}
        <form action="{{ url_for('restaurants.create_post', id=restaurant.id) }}"
          method="post">
          {{ post_form.hidden_tag() }}
          {{ post_form.content(class="span6", placeholder="Post a comment...") }}
          {{ post_form.image(album="comments", class="pull-right") }}
          <input type="submit" class="btn btn-primary pull-right" value="Post comment">
        </form>
      {% include "images/include/image_modal.html" with context %}
      {% endif %}
      <ul class="thumbnails posts" id="posts">
      {% for post in restaurant.posts.paginate(1, per_page=2).items %}
        <li class="span6">
        {{ render_post(post, comment_form) }}
        </li>
      {% endfor %}
      </ul>
    </div>
    <div class="span3">
      <button class="btn btn-block btn-success">
        Follow
      </button>
      <legend>
        Top Dishes
      </legend>
      <ul>
        {% for dish in restaurant.dishes[:10] %}
        <li>
          {{ dish.name|truncate(20) }}
        </li>
        {% endfor %}
      </ul>
      <legend>
        Menus
      </legend>
      <ul>
        {% for menu in restaurant.menus %}
          <li>
            {{ menu.name|truncate(20) }}
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
{% endblock %}

{% block jquery %}
  var page = 1;

  function bind_load_comments(){
    $(".load_comments").on("click", function(ev){
        $(ev.target).hide(); // prevent double click
        var id = $(ev.target).data('id');
        $.get("{{ url_for("restaurants.post_comments") }}" + id + "/",
          function(data){
            $("#comments_" + id).prepend(data);
          }
        );
      }
    );
  }

  bind_load_comments();

  $(window).scroll(function(ev) {
    if($(window).scrollTop() + $(window).height() > $(document).height() - 100) {
      page = page + 1;
      $.ajax({
        url: "{{ url_for("restaurants.more_posts", id=restaurant.id) }}" + page + "/",
        success: function(data){
          $("#posts").append(data);
          $(".load_comments").unbind("click");
          bind_load_comments();
        },
        error: function(){ $(window).unbind("scroll"); }
        }
      );
    }
  });

{% endblock %}

app/templates/restaurants/restaurant_comments.html
{% from "restaurants/macros/post.html" import render_comment %}

{% for comment in comments %}
  <li class="media" id="comment_{{ comment.id }}">
    {{ render_comment(comment) }}
  </li>
{% endfor %}

app/templates/restaurants/restaurant_posts.html
{% from "restaurants/macros/post.html" import render_post %}

{% for post in posts.items %}
  <li class="span6">
    {{ render_post(post, comment_form) }}
  </li>
{% endfor %}

app/templates/restaurants/settings.html
{% extends "base.html" %}

{% from "lib/forms.html" import render_field_inline %}
{% from "lib/navigation.html" import breadcrumbs %}

{% block content %}
  {{ breadcrumbs(restaurant.name,
    (url_for('identities.settings'), 'Settings'),
  ) }}
  <div class="row">

    <div class="span3">
      {% include "identities/settings_nav.html" %}
    </div>

    <div class="span9">
      <legend>
        Places
        <small class="hidden-phone">
          Where your restaurant serves dishes.
        </small>
      </legend>
      {% set places = restaurant.places %}
      {% include("restaurants/include/addresses_table.html") %}
      <a class="btn btn-primary pull-right" href="{{ url_for(
        'restaurants.create_place', id=restaurant.id) }}">
        <i class="icon-plus icon-white"></i> Add an address
      </a>


      <legend>
        Dishes
        <small class="hidden-phone">
          Your entrees, drinks, appetizers, desserts...
        </small>
      </legend>

      {% if restaurant.places.all() %}
        <form method="post" class="form-inline pull-right"
              action="{{ url_for("restaurants.create_dish", id=restaurant.id) }}">
          {{ dish_form.hidden_tag() }}
          {{ render_field_inline(dish_form.name, "create dish", "btn btn-primary",
                                 placeholder="dish's name") }}
        </form>
      {% endif %}
        <div class="clearfix"></div>

      {% set dishes = restaurant.dishes %}
      {% include("restaurants/include/dishes_table.html") %}


      <legend>
        Menu
        <small class="hidden-phone">
          dishes, prices, days and hours or serving.
        </small>
      </legend>

        {% if restaurant.places.all() and restaurant.dishes.all() %}
        <form method="post" class="form-inline pull-right"
              action="{{ url_for("restaurants.create_menu", id=restaurant.id) }}">
          {{ menu_form.hidden_tag() }}
          {{ render_field_inline(menu_form.name, "create menu", "btn btn-primary",
                                 placeholder="menu's name") }}
        </form>
        {% endif %}
        <div class="clearfix"></div>

        {% set menus = restaurant.menus %}
        {% include "restaurants/include/menus_table.html" %}
    </div>
  </div>
{% endblock %}