app/restaurants/forms.py
from flask.ext.wtf import Form, RadioField, TextField, Required, TextArea, \
  Length, FloatField, QuerySelectMultipleField, Select, NumberRange, \
  HiddenInput, QuerySelectField, ValidationError, BooleanField, \
  SelectField, DateTimeField

from app.recipes.models import get_ingredients, get_recipes
from app.images.models import get_images
from app.recipes.constants import CATEGORIES
from app.lib.widgets import auto_complete, Button, image_picker
from app.lib.fields import ListTextField
from app.lib.validators import OptionalIf

import constants as RESTAURANT
from .models import Dish, Menu, MenuDish, Place, get_dishes, get_places


class RestaurantForm(Form):
  category_id = RadioField("Category", choices=RESTAURANT.CATEGORIES,
    coerce=int, widget=Select())
  name = TextField("Restaurant's name", [Required(), Length(min=3, max=255)])


class PlaceForm(Form):
  name = TextField("Name", [Required(), Length(max=255)])
  street = TextField("Street", [Required(), Length(max=1024)])
  zipcode = TextField("Zipcode", [Required(), Length(max=32)])
  city = TextField("City", [Required(), Length(max=255)])
  state = TextField("State", [Required(), Length(max=2)])
  blah = TextField("City",widget=HiddenInput)
  longitude = FloatField(validators=[Required(), NumberRange(min=-180, max=180)])
  latitude = FloatField(validators=[Required(), NumberRange(min=-90, max=90)])

  def __init__(self, *args, **kwargs):
    super(PlaceForm, self).__init__(*args, **kwargs)
    self.place = kwargs.get("obj")
    self.restaurant_id = self.place and self.place.restaurant_id or \
      kwargs.pop("restaurant_id")

  def validate_name(self, field):
    if self.place and self.place.name == field.data:
      return

    if Place.query.filter_by(name=field.data,
                            restaurant_id=self.restaurant_id).all():
      raise ValidationError("Place \"%s\" already exist." % field.data)


class MenuForm(Form):
  name = TextField("Name", [Required(), Length(max=255)])
  monday = BooleanField(widget=Button())
  tuesday = BooleanField("Tuesday", widget=Button())
  wednesday = BooleanField("Wednesday", widget=Button())
  thursday = BooleanField("Thursday", widget=Button())
  friday = BooleanField("Friday", widget=Button())
  saturday = BooleanField("Saturday", widget=Button())
  sunday = BooleanField("Sunday", widget=Button())
  start = DateTimeField("Starts", format="%H:%M")
  stop = DateTimeField("Stops", format="%H:%M")
  places = QuerySelectMultipleField(u"Serving places", get_label="name",
    allow_blank=True, query_factory=get_places, widget=auto_complete)

  def __init__(self, *args, **kwargs):
    super(MenuForm, self).__init__(*args, **kwargs)
    self.menu = kwargs.get("obj")
    self.restaurant_id = self.menu and self.menu.restaurant_id or \
      kwargs.pop("restaurant_id")

  def validate_name(self, field):
    if self.menu and self.menu.name == field.data:
      return

    if Menu.query.filter_by(name=field.data,
                            restaurant_id=self.restaurant_id).all():
      raise ValidationError("Menu \"%s\" already exist." % field.data)


class MenuDishForm(Form):
  price = FloatField("Price", [Required(), NumberRange(min=0)])
  name = TextField("Name", [Required(), Length(max=255)])
  category = SelectField(choices=CATEGORIES, coerce=int)
  description = TextField("Description", widget=TextArea())
  dishes = QuerySelectMultipleField("Dishes", [Required()], get_label="name",
    allow_blank=True, query_factory=get_dishes, widget=auto_complete)

  def __init__(self, *args, **kwargs):
    super(MenuDishForm, self).__init__(*args, **kwargs)
    self.menu_dish = kwargs.get("obj")
    self.menu_id = self.menu_dish and self.menu_dish.menu_id or kwargs.pop("menu_id")

  def validate_name(self, field):
    if self.menu_dish and self.menu_dish.name == field.data:
      return

    if MenuDish.query.filter_by(name=field.data, menu_id=self.menu_id).all():
      raise ValidationError("\"%s\" already exists in this menu." % field.data)

class DishForm(Form):
  name = TextField("Name", [Required(), Length(max=255)])

  def __init__(self, *args, **kwargs):
    super(DishForm, self).__init__(*args, **kwargs)
    self.dish = kwargs.get("obj")
    self.restaurant_id = self.dish and self.dish.restaurant_id or kwargs.pop("restaurant_id")

  def validate_name(self, field):
    if self.dish and self.dish.name == field.data:
      return

    if Dish.query.filter_by(name=field.data,
                            restaurant_id=self.restaurant_id).all():
      raise ValidationError("Dish \"%s\" already exist." % field.data)


class FullDishForm(DishForm):
  category_id = SelectField(choices=CATEGORIES, coerce=int)
  ingredients = QuerySelectMultipleField("Ingredients", [Required()],
    get_label="name", allow_blank=True, query_factory=get_ingredients,
    widget=auto_complete)
  hero_ingredient = QuerySelectField("Hero Ingredient", [Required()],
    get_label="name", allow_blank=True, query_factory=get_ingredients,
    widget=auto_complete)
  recipe = QuerySelectField("Recipe",  [OptionalIf('recipe_suggest')],
    get_label="name", allow_blank=True, query_factory=get_recipes,
    widget=auto_complete)
  description = TextField("Description", widget=TextArea())
  image = QuerySelectField("Update Image", get_label="file",
    allow_blank=True, query_factory=get_images, widget=image_picker)
  ingredients_suggest = ListTextField()
  recipe_suggest = TextField()


class RestaurantPostCommentForm(Form):
  content = TextField("Content", widget=TextArea())


class RestaurantPostForm(Form):
  content = TextField("Content", widget=TextArea())
  image = QuerySelectField("Add an Image", get_label="file",
    allow_blank=True, query_factory=get_images, widget=image_picker)

app/restaurants/views.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask.ext.login import login_required, current_user

from app import db
from app.lib.decorators import remote
from app.recipes.views import suggested_ingredient, suggested_recipe

from .forms import RestaurantForm, MenuForm, DishForm, PlaceForm, MenuDishForm,\
  FullDishForm, RestaurantPostForm, RestaurantPostCommentForm
from .models import Restaurant, Menu, Role, Dish, Place, MenuDish, \
  RestaurantPost, RestaurantPostComment
from .constants import OWNER, RESTAURANT


mod = Blueprint("restaurants", __name__, url_prefix="/restaurants")


def _create_restaurant(name, user, category_id=RESTAURANT):
  restaurant = Restaurant()
  restaurant.name = name
  restaurant.category_id = category_id
  db.session.add(restaurant)

  restaurant_user = Role()
  restaurant_user.restaurant = restaurant
  restaurant_user.user = user
  restaurant_user.role_id = OWNER
  db.session.add(restaurant_user)
  return restaurant


@mod.route("/<int:id>/post/", methods=["POST"])
@login_required
def create_post(id):
  restaurant = Restaurant.query.get_or_404(id)
  form = RestaurantPostForm()
  if form.validate_on_submit():
    post = RestaurantPost()
    post.restaurant = restaurant
    post.author = current_user.user
    post.content = form.content.data
    post.image = form.image.data
    db.session.add(post)
    db.session.commit()
    flash('Your post has been created', 'success')
  else:
    flash('An error occured during the creation of your post', 'error')

  return redirect(url_for("restaurants.view_restaurant", id=restaurant.id))


@mod.route("/<int:id>/post_comment/", methods=["POST"])
@login_required
def create_post_comment(id):
  post = RestaurantPost.query.get_or_404(id)
  form = RestaurantPostCommentForm()
  hashtag = ""
  if form.validate_on_submit():
    comment = RestaurantPostComment()
    comment.post = post
    comment.author = current_user.user
    comment.content = form.content.data
    db.session.add(comment)
    db.session.commit()
    flash('Your comment has been created', 'success')
    hashtag = "#comment_%s" % comment.id

  else:
    flash('An error occured during the creation of your comment', 'error')

  return redirect(
    url_for("restaurants.view_restaurant", id=post.restaurant.id) + hashtag)


@mod.route("/<int:id>/", methods=["GET"])
def view_restaurant(id):
  """
  public facing restaurant page
  """
  restaurant = Restaurant.query.get_or_404(id)
  kwargs = {
    "restaurant": restaurant,
    "posts": restaurant.posts[:10],
  }

  if current_user.is_authenticated():
    kwargs["post_form"] = RestaurantPostForm()
    kwargs["comment_form"] = RestaurantPostCommentForm()

  return render_template("restaurants/restaurant.html", **kwargs)


# first url only present to resolve purpose
@mod.route("/r/comments/", methods=["GET"])
@mod.route("/r/comments/<int:id>/", methods=["GET"])
def post_comments(id=0):
  """
  loads all the comments minus the last 2 ones for a given post
  """
  post = RestaurantPost.query.get_or_404(id)

  return render_template("restaurants/restaurant_comments.html",
    comments=reversed(post.comments[2:]))


@mod.route("/r/<int:id>/", methods=["GET"])
@mod.route("/r/<int:id>/<int:page>/", methods=["GET"])
def more_posts(id, page=1):
  """
  loads another set of post
  """
  restaurant = Restaurant.query.get_or_404(id)
  kwargs = {
    'posts': restaurant.posts.paginate(page, per_page=2)
  }

  if current_user.is_authenticated():
    kwargs["comment_form"] = RestaurantPostCommentForm()

  return render_template("restaurants/restaurant_posts.html", **kwargs)


@mod.route("/<int:id>/edit/", methods=["GET", "POST"])
@login_required
def edit_restaurant(id):
  """
  restaurant edit form
  """
  role = current_user.user.roles.\
    filter_by(role_id=OWNER, restaurant_id=id).first_or_404()
  restaurant = role.restaurant

  form = RestaurantForm(request.form, obj=restaurant)
  if form.validate_on_submit():
    restaurant.category_id = form.category_id.data
    restaurant.name = form.name.data
    db.session.commit()
    return redirect(url_for("restaurants.settings", id=restaurant.id))
  return render_template("restaurants/edit_restaurant.html", form=form,
    restaurant=restaurant)


@mod.route("/create/", methods=["GET", "POST"])
@login_required
def create_restaurant():
  """
  restaurant create form
  """
  form = RestaurantForm(request.form)
  if form.validate_on_submit():
    restaurant = _create_restaurant(
      name=form.name.data,
      user=current_user.user,
      category_id=form.category_id.data
    )
    db.session.add(restaurant)
    db.session.commit()
    return redirect(url_for("restaurants.settings", id=restaurant.id))
  return render_template("restaurants/create_restaurant.html", form=form)


@mod.route("/edit/place/<int:id>/", methods=["GET", "POST"])
@login_required
def edit_place(id):
  """
  Edit a place to be linked to the restaurant
  """
  place = Place.query.filter_by(id=id).first_or_404()

  role = current_user.user.roles.\
    filter_by(role_id=OWNER, restaurant_id=place.restaurant_id).first_or_404()
  restaurant = role.restaurant

  form = PlaceForm(obj=place)
  if form.validate_on_submit():
    place.name = form.name.data
    place.street = form.street.data
    place.city = form.city.data
    place.zipcode = form.zipcode.data
    place.state = form.state.data
    place.longitude = form.longitude.data
    place.latitude = form.latitude.data
    db.session.commit()
    flash("Place successfully saved", "success")
    return redirect(url_for("restaurants.settings", id=restaurant.id))

  return render_template("restaurants/edit_place.html", form=form,
    section="restaurant_%s" % restaurant.id, restaurant=restaurant)


@mod.route("/<int:id>/create/place/", methods=["GET", "POST"])
@login_required
def create_place(id):
  """
  Create a place to be linked to the restaurant
  """
  role = current_user.user.roles.\
    filter_by(role_id=OWNER, restaurant_id=id).first_or_404()
  restaurant = role.restaurant

  form = PlaceForm(restaurant_id=restaurant.id)
  if form.validate_on_submit():
    place = Place()
    place.name = form.name.data
    place.street = form.street.data
    place.city = form.city.data
    place.zipcode = form.zipcode.data
    place.state = form.state.data
    place.longitude = form.longitude.data
    place.latitude = form.latitude.data
    place.restaurant = restaurant
    db.session.add(place)
    db.session.commit()
    flash("Place successfully created", "success")
    return redirect(url_for("restaurants.settings", id=restaurant.id))

  return render_template("restaurants/create_place.html", form=form,
    section="restaurant_%s" % restaurant.id, restaurant=restaurant)


@mod.route("/<int:id>/create/menu/", methods=["GET", "POST"])
@login_required
def create_menu(id):
  """
  Create a menu to be linked to the restaurant
  id = restaurant id where the menu is available
  """
  role = current_user.user.roles.\
    filter_by(role_id=OWNER, restaurant_id=id).first_or_404()
  restaurant = role.restaurant

  form = MenuForm(restaurant_id=restaurant.id)
  if form.validate_on_submit():
    menu = Menu()
    menu.name = form.name.data
    menu.restaurant = restaurant
    db.session.add(menu)
    db.session.commit()
    flash("Menu successfully created", "success")
    return redirect(url_for("restaurants.edit_menu", id=menu.id))

  return render_template("restaurants/create_menu.html", form=form,
    restaurant=restaurant)


@mod.route("/menu/<int:id>/edit/", methods=["GET", "POST"])
@login_required
def edit_menu(id):
  """
  Edit a menu
  """
  menu = Menu.query.get_or_404(id)

  role = current_user.user.roles.\
    filter_by(role_id=OWNER, restaurant_id=menu.restaurant.id).first_or_404()
  restaurant = role.restaurant

  form = MenuForm(request.form, obj=menu)
  if form.validate_on_submit():
    menu.name = form.name.data
    menu.places = form.places.data
    menu.monday = form.monday.data
    menu.tuesday = form.tuesday.data
    menu.wednesday = form.wednesday.data
    menu.thursday = form.thursday.data
    menu.friday = form.friday.data
    menu.saturday = form.saturday.data
    menu.sunday = form.sunday.data
    menu.start = form.start.data.time()
    menu.stop = form.stop.data.time()
    db.session.commit()
    flash("Menu successfully saved.", "success")
    return redirect(url_for("restaurants.settings", id=restaurant.id))

  return render_template("restaurants/edit_menu.html", form=form,
    menu=menu, restaurant=restaurant,
    menu_dish_form=MenuDishForm(prefix="md_", menu_id=menu.id))


@mod.route("/menu/dish/delete/<int:id>/", methods=["POST"])
@login_required
def delete_menu_dish(id):
  menu_dish = MenuDish.query.get(id)

  current_user.user.roles.filter_by(restaurant_id=menu_dish.menu.restaurant_id,
                                    role_id=OWNER).first_or_404()

  db.session.delete(menu_dish)
  db.session.commit();
  flash("Dish %s has been removed from this menu." % menu_dish.name, "success")
  return redirect(url_for("restaurants.edit_menu", id=menu_dish.menu_id))


@mod.route("/dish/<int:id>/edit/", methods=["GET", "POST"])
@login_required
def edit_dish(id):
  """
  Edit a dish
  """
  dish = Dish.query.get_or_404(id)

  role = current_user.user.roles.\
    filter_by(role_id=OWNER, restaurant_id=dish.restaurant_id).first_or_404()
  restaurant = role.restaurant

  form = FullDishForm(request.form, obj=dish)
  if form.validate_on_submit():
    dish.name = form.name.data
    dish.description = form.description.data
    dish.category_id = form.category_id.data
    dish.hero_ingredient = form.hero_ingredient.data
    dish.ingredients = form.ingredients.data

    for ingredient in form.ingredients_suggest.data:
      ingredient = suggested_ingredient(ingredient)
      if ingredient:
        dish.ingredients.append(ingredient)

    if form.recipe_suggest.data:
      dish.recipe = suggested_recipe(form.recipe_suggest.data,

app/templates/restaurants/include/addresses_table.html
{% for place in places %}
  {% if loop.first %}
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Street</th>
          <th>Zipcode</th>
          <th>City</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
  {% endif %}
  <tr>
    <td>
      <a href="{{ url_for("restaurants.edit_place", id=place.id) }}">
        <strong> {{ place.name }} </strong>
      </a>
    </td>
    <td>{{ place.street }}</td>
    <td>{{ place.zipcode }}</td>
    <td>{{ place.city }}</td>
  </tr>
  {% if loop.last %}
      </tbody>
    </table>
  {% endif %}
{% else %}
  <div class="alert alert-warning">
    You haven't yet published any places. We won't be able to publicly
    list {{ restaurant.name }} until you provide those key informations.
  </div>
{% endfor %}

app/templates/restaurants/include/dishes_table.html
{% for dish in dishes %}
  {% if loop.first %}
    <table class="table table-striped">
      <thead>
        <tr>
          <th>
            Dish
          </th>
          <th>
            Category
          </th>
          <th>
            Recipe
          </th>
          <th>
            Ingredients
          </th>
        </tr>
      </thead>
    <tbody>
  {% endif %}
    <tr>
      <td>
        <a href="{{ url_for("restaurants.edit_dish", id=dish.id) }}">
          <strong>{{ dish.name }}</strong>
        </a>
      </td>
      <td>
        {{ dish.category }}
      </td>
      <td>
        {{ dish.recipe.name }}
      </td>
      <td>
        {% for ingredient in dish.ingredients %}
          {{- ingredient.name -}}
          {% if not loop.last %},{% endif %}
        {% endfor %}
      </td>
    </tr>
  {% if loop.last %}
    </tbody>
  </table>
  {% endif %}
  {% else %}
    <div class="alert alert-warning">
      You haven't yet created any dishes. We won't be able to publicly
      list {{ restaurant.name }} until you tell us what delicious meal
      you are offering to our starving gourmet.
    </div>
{% endfor %}

app/templates/restaurants/include/menu_dishes_table.html
{% for menu_dish in menu_dishes %}
  {% if loop.first %}
    <table class="table table-striped">
      <thead>
        <tr>
          <th>
            name
          </th>
          <th>
            Dish(es)
          </th>
          <th>
            Price
          </th>
          <th>
            Description
          </th>
        </tr>
      </thead>
    <tbody>
  {% endif %}
    <tr>
      <td>
        <strong>
          {{ menu_dish.name }}
        </strong>
      </td>
      <td>
        {% for dish in menu_dish.dishes %}
          <a href="{{ url_for("restaurants.edit_dish", id=dish.id) }}">
            {{ dish.name }}
          </a>
          {{ "," if not loop.last }}
        {% endfor %}
      </td>
      <td>
        ${{ "%.2f" % menu_dish.price }}
      </td>
      <td>
        {{ menu_dish.description|truncate(60) }}
      </td>
      <td>
        <form action="{{ url_for("restaurants.delete_menu_dish", id=menu_dish.id) }}"
              method="post" style="margin: 0">
          <button type="submit" class="btn btn-danger">
            <i class="icon-trash icon-white"></i> Delete
          </button>
        </form>
      </td>
    </tr>
  {% if loop.last %}
    </tbody>
  </table>
  {% endif %}
  {% else %}
    <div class="alert alert-warning">
      You haven't yet associated any dishes with this menu. Start adding
      some using <a onclick="$('#id_md_dishes').focus()" href="#">
      <strong>the form on the top right.</strong><a>
    </div>
{% endfor %}

app/templates/restaurants/include/menus_table.html
{% for menu in menus %}
  {% if loop.first %}
    <table class="table table-striped">
      <thead>
        <tr>
          <th>
            Menu
          </th>
          <th>
            Hours
          </th>
          <th>
            Days
          </th>
          <th>
            Dishes
          </th>
          <th>
            Places
          </th>
        </tr>
      </thead>
    <tbody>
  {% endif %}
    <tr>
      <td>
        <a href="{{ url_for("restaurants.edit_menu", id=menu.id) }}">
          <strong>{{ menu.name }}</strong>
        </a>
      </td>
      <td>
        {% if menu.start and menu.stop %}
          from {{ menu.start.strftime('%I:%M %p') }}
          to {{ menu.stop.strftime('%I:%M %p') }}
        {% else %}
          Hours undefined yet.
        {% endif %}
      </td>
      <td>
        {{ menu.serving_days }}
      </td>
      <td>
        {{ menu.dishes|count }}
      </td>
      <td>
        {{ menu.places|count }}
      </td>
    </tr>
  {% if loop.last %}
    </tbody>
  </table>
  {% endif %}
{% else %}
  <div class="alert alert-warning">
    You haven't yet setup any menu. Menu will let you indicate price,
        locaction and hours of serving. We won't be able to publicly list
    {{ restaurant.name }} until you provide those key informations.
  </div>
{% endfor %}