app/recipes/models.py
from app import db

from .constants import CATEGORIES, VALID, STATUS, ENTREE


# ManyToMany tables
recipes_ingredients = db.Table('recipes_ingredients',
  db.Column('ingredient_id', db.Integer, db.ForeignKey('recipes_ingredient.id')),
  db.Column('recipe_id', db.Integer, db.ForeignKey('recipes_recipe.id'))
)

recipe_tags = db.Table('recipes_recipe_tags',
  db.Column('tag_id', db.Integer, db.ForeignKey('recipes_tag.id')),
  db.Column('recipe_id', db.Integer, db.ForeignKey('recipes_recipe.id'))
)

ingredient_categories = db.Table('recipes_ingredient_categories',
  db.Column('category_id', db.Integer, db.ForeignKey('recipes_ingredient_category.id')),
  db.Column('ingredient_id', db.Integer, db.ForeignKey('recipes_ingredient.id'))
)

ingredients_ingredients = db.Table('recipes_ingredients_ingredients',
  db.Column('parent_ingredient_id', db.Integer,
    db.ForeignKey('recipes_ingredient.id'), primary_key=True),
  db.Column('child_ingredient_id', db.Integer,
    db.ForeignKey('recipes_ingredient.id'), primary_key=True)
)


class Tag(db.Model):
  """
  Tag associated with recipes
  """
  __tablename__ = 'recipes_tag'

  name = db.Column(db.String(255))
  id = db.Column(db.Integer, primary_key=True)


class Recipe(db.Model):
  __tablename__ = 'recipes_recipe'

  id = db.Column(db.Integer, primary_key=True)
  name = db.Column(db.String(255), unique=True)
  category_id = db.Column(db.Integer, default=ENTREE)
  status_id = db.Column(db.Integer, default=VALID)

  tags = db.relationship('Tag', secondary=recipe_tags,
      backref=db.backref('recipes', lazy='dynamic'))
  ingredients = db.relationship('Ingredient', secondary=recipes_ingredients,
      backref=db.backref('recipes', lazy='dynamic'))

  @property
  def category(self):
    return dict(CATEGORIES)[self.category_id]

  @property
  def status(self):
    return dict(STATUS)[self.status_id]

  def __repr__(self):
    return u"<Recipe:%d %s>" % (self.id, self.name)


class Ingredient(db.Model):
  __tablename__ = 'recipes_ingredient'

  id = db.Column(db.Integer, primary_key=True)
  name = db.Column(db.String(255), unique=True)
  status_id = db.Column(db.Integer, default=VALID)

  parents = db.relationship('Ingredient', secondary=ingredients_ingredients,
          primaryjoin=id==ingredients_ingredients.c.child_ingredient_id,
          secondaryjoin=id==ingredients_ingredients.c.parent_ingredient_id,
          backref=db.backref('children', lazy='dynamic'))
  categories = db.relationship('IngredientCategory', secondary=ingredient_categories,
          backref=db.backref('ingredients', lazy='dynamic'))

  def __contains__(self, item):
    if item.id == self.id:
      return True
    return any(item in parent for parent in self.parents)

  @property
  def status(self):
    return dict(STATUS)[self.status_id]

  def __repr__(self):
    return u"<Ingredient:%d %s>" % (self.id, self.name)


class IngredientCategory(db.Model):
  __tablename__ = 'recipes_ingredient_category'

  id = db.Column(db.Integer, primary_key=True)
  name = db.Column(db.String(255), unique=True)

  def __repr__(self):
    return u"<IngredientCategory:%d %s>" % (self.id, self.name)


# query factories
def get_ingredients():
  return Ingredient.query.filter()


def get_categories():
  return IngredientCategory.query.filter()


def get_tags():
  return Tag.query.filter()


def get_recipes():
  return Recipe.query.filter()

app/recipes/forms.py
from flask.ext.wtf import Form, TextField, Required, QuerySelectMultipleField, \
  Length, ValidationError, SelectField, QuerySelectField
from app.lib.widgets import auto_complete
from app.lib.fields import ListTextField

from .models import IngredientCategory, Recipe, Ingredient, get_ingredients, \
  Tag, get_categories, get_recipes, get_tags
from .constants import CATEGORIES, STATUS

class IngredientForm(Form):
  name = TextField("Ingredient's name", [Required(), Length(min=3, max=255)])

  def __init__(self, *args, **kwargs):
    super(IngredientForm, self).__init__(*args, **kwargs)
    self.ingredient = kwargs.get('obj')

  def validate_name(self, field):
    if self.ingredient and self.ingredient.name == field.data:
      return

    if Ingredient.query.filter_by(name=field.data).all():
      raise ValidationError('Ingredient "%s" already exist.' % field.data)


class SubstituteIngredientForm(Form):
  ingredient = QuerySelectField(u'Ingredient', get_label='name', allow_blank=False,
    query_factory=get_ingredients, widget=auto_complete)


class FullIngredientForm(IngredientForm):
  parents = QuerySelectMultipleField(u'Parent', get_label='name', allow_blank=True,
    query_factory=get_ingredients, widget=auto_complete)
  categories = QuerySelectMultipleField(u'Category', get_label='name', allow_blank=True,
    query_factory=get_categories, widget=auto_complete)
  status_id = SelectField('Status', [Required()], choices=STATUS, coerce=int)


class SubstituteRecipeForm(Form):
  recipe = QuerySelectField(u'Recipe', get_label='name', allow_blank=False,
    query_factory=get_recipes, widget=auto_complete)


class RecipeForm(Form):
  name = TextField("Recipe's name", [Required(), Length(min=3, max=255)])

  def __init__(self, *args, **kwargs):
    super(RecipeForm, self).__init__(*args, **kwargs)
    self.recipe = kwargs.get('obj')

  def validate_name(self, field):
    if self.recipe and self.recipe.name == field.data:
      return

    if Recipe.query.filter_by(name=field.data).all():
      raise ValidationError('Recipe "%s" already exist.' % field.data)


class FullRecipeForm(RecipeForm):
  category_id = SelectField(choices=CATEGORIES, coerce=int)
  ingredients_suggest = ListTextField()
  status_id = SelectField('Status', choices=STATUS, coerce=int)
  tags = QuerySelectMultipleField('Tag', get_label='name', allow_blank=True,
    query_factory=get_tags, widget=auto_complete)
  ingredients = QuerySelectMultipleField(u'Ingredients', get_label='name', allow_blank=True,
    query_factory=get_ingredients, widget=auto_complete)


class TagForm(Form):
  name = TextField("Tag's name", [Required(), Length(min=3, max=255)])

  def __init__(self, *args, **kwargs):
    super(TagForm, self).__init__(*args, **kwargs)
    self.tag = kwargs.get('obj')

  def validate_name(self, field):
    if self.tag and self.tag.name == field.data:
      return

    if Tag.query.filter_by(name=field.data).all():
      raise ValidationError('Tag "%s" already exist.' % field.data)


class IngredientCategoryForm(Form):
  name = TextField("Category's name", [Required(), Length(min=3, max=255)])

  def __init__(self, *args, **kwargs):
    super(IngredientCategoryForm, self).__init__(*args, **kwargs)
    self.category = kwargs.get('obj')

  def validate_name(self, field):
    if self.category and self.category.name == field.data:
      return

    if IngredientCategory.query.filter_by(name=field.data).all():
      raise ValidationError('Category "%s" already exist.' % field.data)

class FilterForm(Form):
  name = TextField("Filter by name")

app/recipes/views.py
from flask import Blueprint, render_template, flash, redirect, url_for, \
  request, Markup
from flask.ext.login import fresh_login_required

from app import db
from app.lib.decorators import remote

from app.identities.decorators import admin_required
from .models import Recipe, Ingredient, IngredientCategory, Tag
from .constants import SUGGESTION, VALID
from .forms import IngredientCategoryForm, IngredientForm, FullIngredientForm,\
  RecipeForm, FullRecipeForm, SubstituteIngredientForm, FilterForm, \
  SubstituteRecipeForm, TagForm

mod = Blueprint('recipes', __name__, url_prefix='/recipes')


@mod.route('/ingredient/edit/<int:id>/', methods=['GET', 'POST'])
@mod.route('/ingredient/edit/<int:id>/<int:page>/', methods=['GET', 'POST'])
@fresh_login_required
@admin_required
def edit_ingredient(id, page=1):
  ingredient = Ingredient.query.get_or_404(id)

  form = FullIngredientForm(obj=ingredient)
  if form.validate_on_submit():
    ingredient.name = form.name.data
    # prevent infinite recursive relation like x -> y -> z -> x -> y -> z...
    # by removing parent being child of the current ingredient
    ingredient.parents = [p for p in form.parents.data if ingredient not in p]
    ingredient.categories = form.categories.data
    ingredient.status_id = form.status_id.data
    db.session.commit()
    flash('Ingredient successfully updated', 'success')
    return redirect(url_for('recipes.ingredients'))

  kwargs = {
    "form": form,
    "ingredient": ingredient,
    "recipes": ingredient.recipes.order_by('name'),
    "ingredients": ingredient.children.order_by('name').paginate(page),
  }

  if ingredient.status_id == SUGGESTION:
    kwargs['substitute_form'] = SubstituteIngredientForm()

  return render_template("recipes/edit_ingredient.html", **kwargs)


@mod.route('/tag/<int:id>/delete/', methods=['POST'])
@fresh_login_required
@admin_required
def delete_tag(id):
  tag = Tag.query.get_or_404(id)
  db.session.delete(tag)
  db.session.commit()
  flash("Tag %s deleted." % tag.name, 'success')
  return redirect(url_for('recipes.tags'))


@mod.route('/ingredient/<int:id>/delete/', methods=['POST'])
@fresh_login_required
@admin_required
def delete_ingredient(id):
  ingredient = Ingredient.query.get_or_404(id)
  db.session.delete(ingredient)
  db.session.commit()
  flash("Ingredient %s deleted." % ingredient.name, 'success')
  return redirect(url_for('recipes.ingredients'))


@mod.route('/recipe/<int:id>/substitute/',  methods=['POST'])
@fresh_login_required
@admin_required
def recipe_substitute(id):
  recipe = Recipe.query.get_or_404(id)
  form = SubstituteRecipeForm()
  if form.validate_on_submit():
    substitute = form.recipe.data
    for dish in recipe.dishes:
      if dish.recipe_id != substitute.id:
        dish.recipe = substitute
    db.session.delete(recipe)
    db.session.commit()
    flash(
      Markup('Recipe <strong>%s</strong> substituted by <strong>%s</strong>')\
      % (recipe.name, substitute.name), 'success')
    return redirect(url_for('recipes.edit_recipe', id=substitute.id))
  return redirect(url_for('recipes.edit_recipe', id=recipe.id))


@mod.route('/ingredient/<int:id>/substitute/', methods=['POST'])
@fresh_login_required
@admin_required
def ingredient_substitute(id):
  ingredient = Ingredient.query.get_or_404(id)
  form = SubstituteIngredientForm()
  if form.validate_on_submit():
    substitute = form.ingredient.data
    for recipe in ingredient.recipes:
      if substitute not in recipe.ingredients:
        recipe.ingredients.append(substitute)
    for dish in ingredient.dishes:
      if substitute not in dish.ingredients:
        dish.ingredients.append(substitute)
    db.session.delete(ingredient)
    db.session.commit()
    flash(
      Markup('Ingredient <strong>%s</strong> substituted by <strong>%s</strong>')\
      % (ingredient.name, substitute.name), 'success')
    return redirect(url_for('recipes.edit_ingredient', id=substitute.id))
  return redirect(url_for('recipes.edit_ingredient', id=ingredient.id))


@mod.route('/ingredient/suggestions/', methods=['GET', 'POST'])
@mod.route('/ingredient/suggestions/<int:page>/', methods=['GET', 'POST'])
@fresh_login_required
@admin_required
def ingredient_suggestions(page=1):
  return render_template("recipes/ingredient_suggestions.html",
    ingredients=Ingredient.query.filter_by(status_id=SUGGESTION).\
      order_by('name').paginate(page))


@mod.route('/ingredients/', methods=['GET', 'POST'])
@mod.route('/ingredients/<int:page>/', methods=['GET', 'POST'])
@fresh_login_required
@admin_required
def ingredients(page=1):
  form = IngredientForm()
  if form.validate_on_submit():
    ingredient = Ingredient()
    ingredient.name = form.name.data
    db.session.add(ingredient)
    db.session.commit()
    flash('Ingredient successfully created', 'success')
    return redirect(url_for('recipes.edit_ingredient', id=ingredient.id))

  args = [Ingredient.status_id == VALID]

  filter_form = FilterForm(request.args, prefix='filter', csrf_enabled=False)
  if filter_form.validate() and filter_form.name.data:
    args.append(Ingredient.name.like('%%%s%%' % filter_form.name.data))

  return render_template("recipes/ingredients.html", form=form,
    filter_form=filter_form,
    ingredients=Ingredient.query.filter(*args).order_by('name').paginate(page))


@mod.route('/category/edit/<int:id>/', methods=['GET', 'POST'])
@mod.route('/category/edit/<int:id>/<int:page>/', methods=['GET', 'POST'])
@fresh_login_required
@admin_required
def edit_category(id, page=1):
  category = IngredientCategory.query.get_or_404(id)
  form = IngredientCategoryForm(obj=category)
  if form.validate_on_submit():
    category.name = form.name.data
    db.session.commit()
    flash('Category successfully updated', 'success')
    return redirect(url_for('recipes.categories'))

  return render_template("recipes/edit_category.html", form=form,
    ingredients=category.ingredients.order_by('name').paginate(page),
    category=category)


@mod.route('/categories/', methods=['GET', 'POST'])
@mod.route('/categories/<int:page>/', methods=['GET', 'POST'])
@fresh_login_required
@admin_required
def categories(page=1):
  form = IngredientCategoryForm()
  if form.validate_on_submit():
    category = IngredientCategory()
    category.name = form.name.data
    db.session.add(category)
    db.session.commit()
    flash('Category successfully created', 'success')
    return redirect(url_for('recipes.categories'))

  args = []
  filter_form = FilterForm(request.args, prefix='filter', csrf_enabled=False)
  if filter_form.validate() and filter_form.name.data:
    args.append(IngredientCategory.name.like('%%%s%%' % filter_form.name.data))

  return render_template("recipes/categories.html", form=form,
    categories=IngredientCategory.query.filter(*args).\
      order_by('name').paginate(page), filter_form=filter_form)


@mod.route('/tag/edit/<int:id>/', methods=['GET', 'POST'])
@mod.route('/tag/edit/<int:id>/<int:page>/', methods=['GET', 'POST'])
@fresh_login_required
@admin_required
def edit_tag(id, page=1):
  tag = Tag.query.get_or_404(id)
  form = TagForm(obj=tag)
  if form.validate_on_submit():
    tag.name = form.name.data
    db.session.commit()
    flash('Tag successfully updated', 'success')
    return redirect(url_for('recipes.tags'))

  return render_template("recipes/edit_tag.html", form=form,
    recipes=tag.recipes.order_by('name').paginate(page),
    tag=tag)


@mod.route('/tags/', methods=['GET', 'POST'])
@mod.route('/tags/<int:page>/', methods=['GET', 'POST'])
@fresh_login_required
@admin_required
def tags(page=1):
  form = TagForm()
  if form.validate_on_submit():
    tag = Tag(name=form.name.data)
    db.session.add(tag)
    db.session.commit()
    flash('Tag successfully created', 'success')
    return redirect(url_for('recipes.tags'))

  args = []
  filter_form = FilterForm(request.args, prefix='filter', csrf_enabled=False)
  if filter_form.validate() and filter_form.name.data:
    args.append(Tag.name.like('%%%s%%' % filter_form.name.data))

  return render_template("recipes/tags.html", form=form,
    tags=Tag.query.filter(*args).order_by('name').paginate(page),
    filter_form=filter_form)


@mod.route('/recipes/suggestions/', methods=['GET', 'POST'])
@mod.route('/recipes/suggestions/<int:page>/', methods=['GET', 'POST'])
@fresh_login_required
@admin_required
def recipe_suggestions(page=1):
  return render_template("recipes/recipe_suggestions.html",
    recipes=Recipe.query.filter_by(status_id=SUGGESTION).\
      order_by('name').paginate(page))


@mod.route('/recipes/', methods=['GET', 'POST'])
@mod.route('/recipes/<int:page>/', methods=['GET', 'POST'])
@fresh_login_required
@admin_required
def recipes(page=1):
  form = RecipeForm()
  if form.validate_on_submit():
    recipe = Recipe()
    recipe.name = form.name.data
    db.session.add(recipe)
    db.session.commit()
    flash('Recipe successfully created', 'success')
    return redirect(url_for('recipes.edit_recipe', id=recipe.id))

  args = [Recipe.status_id == 1]
  filter_form = FilterForm(request.args, prefix='filter', csrf_enabled=False)
  if filter_form.validate() and filter_form.name.data:
    args.append(Recipe.name.like('%%%s%%' % filter_form.name.data))

  return render_template("recipes/recipes.html", form=form,
    filter_form=filter_form,
    recipes=Recipe.query.filter(*args).order_by('name').paginate(page))


def suggested_ingredient(name):
  """
  get or create the ingredient
  """
  name = name.lower().strip()
  ingredient_form = IngredientForm(csrf_enabled=False, name=name)
  if ingredient_form.validate():
    # first try to find the ingredient
    ingredient = Ingredient.query.filter_by(name=name).first()
    if ingredient:
      return ingredient

    ingredient = Ingredient(name=name)
    ingredient.status_id = SUGGESTION
    return ingredient


def suggested_recipe(name, **kwargs):
  name = name.lower().strip()
  recipe_form = FullRecipeForm(csrf_enabled=False, name=name,

app/templates/recipes/categories.html
{% extends "base.html" %}

{% from "lib/pagination.html" import render_pagination with context %}
{% from "lib/forms.html" import render_field_inline %}
{% from "lib/navigation.html" import breadcrumbs, admin_tabs %}

{% block content %}
  {{ breadcrumbs('Categories',
    (url_for('identities.settings'), 'Settings'),
  ) }}
  {{ admin_tabs('categories') }}
  <form method="post" class="form-inline pull-right">
    {{ form.hidden_tag() }}
    {{ render_field_inline(form.name, 'add category', 'btn', placeholder="Category's name") }}
  </form>
  <form method="get" action="{{ url_for('recipes.categories') }}"
        class="form-inline pull-left">
    {{ render_field_inline(filter_form.name, 'filter', 'btn',
                           placeholder=filter_form.name.label.text) }}
  </form>

  <div class="clearfix"></div>

  {% include("recipes/include/categories_table.html") %}
  {{ render_pagination(categories, 'recipes.categories') }}
{% endblock %}

app/templates/recipes/edit_category.html
{% extends "base.html" %}

{% from "lib/pagination.html" import render_pagination with context %}
{% from "lib/forms.html" import render_field %}
{% from "lib/navigation.html" import breadcrumbs %}

{% block content %}
  {{ breadcrumbs('Edit Category',
    (url_for('identities.settings'), 'Settings'),
    (url_for('recipes.categories'), 'Categories'),
  ) }}
  <legend>Edit Category</legend>
  <form method="post" class="form-horizontal">
    {{ form.hidden_tag() }}
    {{ render_field(form.name) }}
    <div class="form-actions">
      <button type="submit" id="save_btn" class="btn btn-success">
        <i class="icon-ok icon-white"></i> Update category
      </button>
      <a class="btn" href="{{ url_for('recipes.categories') }}">
        Cancel
      </a>
    </div>
  </form>
  <legend>Ingredients belonging to "{{ category.name }}"</legend>
  {{ render_pagination(ingredients, 'recipes.edit_category', id=category.id) }}
  {% include("recipes/include/ingredients_table.html") %}
  {{ render_pagination(ingredients, 'recipes.edit_category', id=category.id) }}
{% endblock %}

app/templates/recipes/edit_ingredient.html
{% extends "base.html" %}

{% from "lib/pagination.html" import render_pagination with context %}
{% from "lib/forms.html" import render_field, render_field_inline %}
{% from "lib/navigation.html" import breadcrumbs %}

{% block content %}
  {{ breadcrumbs('Edit Ingredient',
    (url_for('identities.settings'), 'Settings'),
    (url_for('recipes.ingredients'), 'Ingredients'),
  ) }}
  <div class="row">
    <form method="post" class="hidden" name="delete_ingredient"
      action="{{ url_for("recipes.delete_ingredient", id=ingredient.id) }}">
    </form>
    <form method="post" class="form-horizontal{{ " span6" if substitute_form }}">
      <legend>Edit Ingredient <small>{{ ingredient.status }}</small></legend>
      {{ form.hidden_tag() }}
      {{ render_field(form.name) }}
      {{ render_field(form.categories, data_url=url_for('recipes.remote_categories'),
        placeholder="start typing a category...") }}
      {{ render_field(form.parents, data_url=url_for('recipes.remote_ingredients'),
        placeholder="start typing an ingredient...") }}
      {{ render_field(form.status_id) }}
      <div class="form-actions btn-toolbar">
        <div class="btn-group">
          <button type="submit" id="save_btn" class="btn btn-success">
            <i class="icon-ok icon-white"></i> Update ingredient
          </button>
          <button class="btn btn-success dropdown-toggle" data-toggle="dropdown">
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <li>
              <a href="#" onclick="document.delete_ingredient.submit()">
                <i class="icon-trash"></i> Delete ingredient
              </a>
            </li>
          </ul>
        </div>
        <a class="btn" href="{{ url_for('recipes.ingredients') }}">
          Cancel
        </a>
      </div>
    </form>
    {% if substitute_form %}
      <form method="post" class="form-horizontal span6"
          action="{{ url_for('recipes.ingredient_substitute', id=ingredient.id) }}">
      <legend>Substitute Ingredient</legend>
      <div class="alert alert-info">
        <strong>Substitute</strong> feature will delete this suggested
        ingredient and replace it in every recipe and dish where it has
        been added with the ingredient picked bellow.
      </div>
      {{ substitute_form.hidden_tag() }}
      {{ render_field(substitute_form.ingredient,
        data_url=url_for('recipes.remote_ingredients'),
        placeholder="start typing an ingredient...") }}
        <div class="form-actions">
          <button type="submit" id="save_btn" class="btn btn-success">
            <i class="icon-ok icon-white"></i> Substitute ingredient
          </button>
        </div>
      </form>
    {% endif %}
  </div>
  <legend>Children ingredients</legend>
  {{ render_pagination(ingredients, 'recipes.edit_ingredient', id=ingredient.id) }}
  {% include("recipes/include/ingredients_table.html") %}
  <legend>Recipes containing {{ ingredient.name }}</legend>
  {% include("recipes/include/recipes_table.html") %}
{% endblock %}

{% block bootstrap %}
  $script('{{url_for('static', filename="js/autocomplete.js")}}', 'autocomplete');
{% endblock %}

app/templates/recipes/edit_recipe.html
{% extends "base.html" %}

{% from "lib/pagination.html" import render_pagination %}
{% from "lib/forms.html" import render_field %}
{% from "lib/navigation.html" import breadcrumbs %}

{% block content %}
  {{ breadcrumbs('Edit recipe',
    (url_for('identities.settings'), 'Settings'),
    (url_for('recipes.recipes'), 'Recipes'),
  ) }}
  <div class="row">
    <form method="post" class="form-horizontal{{ " span6" if substitute_form }}">
      <legend>Edit Recipe <small>{{ recipe.status }}</small></legend>
      {{ form.hidden_tag() }}
      {{ render_field(form.name) }}
      {{ render_field(form.category_id) }}
      {{ render_field(form.ingredients, data_url=url_for('recipes.remote_ingredients'),
        data_suggest="True",
        placeholder="start typing an ingredient...") }}
      {{ render_field(form.tags, data_url=url_for('recipes.remote_tags'),
        placeholder="start typing a tag...") }}
      {{ render_field(form.status_id) }}
      <div class="form-actions">
        <button type="submit" id="save_btn" class="btn btn-success">
          <i class="icon-ok icon-white"></i> Update recipe
        </button>
        <a class="btn" href="{{ url_for('recipes.recipes') }}">
          Cancel
        </a>
      </div>
    </form>
    {% if substitute_form %}
      <form method="post" class="form-horizontal span6"
          action="{{ url_for('recipes.recipe_substitute', id=recipe.id) }}">
      <legend>Substitute Recipe</legend>
      <div class="alert alert-info">
        <strong>Substitute</strong> feature will delete this suggested
        recipe and replace it in every dish with the recipe picked bellow.
      </div>
      {{ substitute_form.hidden_tag() }}
      {{ render_field(substitute_form.recipe,
        data_url=url_for('recipes.remote_recipes'),
        placeholder="start typing an recipe...") }}
        <div class="form-actions">
          <button type="submit" id="save_btn" class="btn btn-success">
            <i class="icon-ok icon-white"></i> Substitute recipe
          </button>
        </div>
      </form>
    {% endif %}
  </div>
  <legend>Dishes using "{{ recipe.name }}"</legend>
  {{ render_pagination(dishes, 'recipes.edit_recipe', id=recipe.id) }}
  {% include("recipes/include/dishes_table.html") %}
  {{ render_pagination(dishes, 'recipes.edit_recipe', id=recipe.id) }}
{% endblock %}

{% block bootstrap %}
  $script('{{url_for('static', filename="js/autocomplete.js")}}', 'autocomplete');
{% endblock %}

app/templates/recipes/edit_tag.html
{% extends "base.html" %}

{% from "lib/pagination.html" import render_pagination with context %}
{% from "lib/forms.html" import render_field %}
{% from "lib/navigation.html" import breadcrumbs %}

{% block content %}
  {{ breadcrumbs('Edit Tag',
    (url_for('identities.settings'), 'Settings'),
    (url_for('recipes.tags'), 'Tags'),
  ) }}
  <legend>Edit Tag</legend>
  <form method="post" class="hidden" name="delete_tag"
    action="{{ url_for("recipes.delete_tag", id=tag.id) }}">
  </form>
  <form method="post" class="form-horizontal">
    {{ form.hidden_tag() }}
    {{ render_field(form.name) }}
    <div class="form-actions btn-toolbar">
      <div class="btn-group">
        <button type="submit" id="save_btn" class="btn btn-success">
          <i class="icon-ok icon-white"></i> Update tag
        </button>
        <button class="btn btn-success dropdown-toggle" data-toggle="dropdown">
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <li>
            <a href="#" onclick="document.delete_tag.submit()">
              <i class="icon-trash"></i> Delete tag
            </a>
          </li>
        </ul>
      </div>
      <a class="btn" href="{{ url_for('recipes.tags') }}">
        Cancel
      </a>
    </div>
  </form>
  <legend>Recipes associated with "{{ tag.name }}"</legend>
  {{ render_pagination(recipes, 'recipes.edit_tag', id=tag.id) }}
  {% include("recipes/include/recipes_table.html") %}
  {{ render_pagination(recipes, 'recipes.edit_tag', id=tag.id) }}
{% endblock %}

app/templates/recipes/recipes.html
{% extends "base.html" %}

{% from "lib/pagination.html" import render_pagination with context %}
{% from "lib/forms.html" import render_field_inline %}
{% from "lib/navigation.html" import breadcrumbs, admin_tabs %}

{% block content %}
  {{ breadcrumbs('Recipes',
    (url_for('identities.settings'), 'Settings'),
  ) }}
  {{ admin_tabs('recipes') }}
  <form method="post" class="form-inline pull-right">
    {{ form.hidden_tag() }}
    {{ render_field_inline(form.name, 'add recipe', 'btn', placeholder="Recipe's name") }}
  </form>
  <form method="get" action="{{ url_for('recipes.recipes') }}"
        class="form-inline pull-left">
    {{ render_field_inline(filter_form.name, 'filter', 'btn',
                           placeholder=filter_form.name.label.text) }}
  </form>

  <div class="clearfix"></div>

  {% include("recipes/include/recipes_table.html") %}
  {{ render_pagination(recipes, 'recipes.recipes') }}
{% endblock %}