app/identities/views.py
from werkzeug import check_password_hash, generate_password_hash
from flask import Blueprint, request, render_template, flash, redirect, url_for
from flask.ext.login import login_user, login_required, current_user, \
  logout_user, fresh_login_required

from app import db

from forms import RegisterForm, LoginForm, ProfileForm, EmailForm, PasswordForm
from models import User, Identity

from app.restaurants.forms import RestaurantForm
from app.restaurants.views import _create_restaurant


mod = Blueprint('identities', __name__, url_prefix='/identities')


@mod.context_processor
def inject_login_form():
  return {'login_form': LoginForm()}


@mod.route('/settings/', methods=['GET', 'POST'])
@fresh_login_required
def settings():
  profile_form = ProfileForm(obj=current_user.user)
  email_form = EmailForm(obj=current_user)
  password_form = PasswordForm()
  if 'new_email' in request.form and email_form.validate_on_submit():
    current_user.email = email_form.new_email.data
    db.session.commit()
    flash('Your email address has been successfully updated.', 'success')
    return redirect(url_for('identities.settings'))

  elif 'password' in request.form and password_form.validate_on_submit():
    current_user.password = generate_password_hash(password_form.password.data)
    db.session.commit()
    flash('Your password has been successfully updated.', 'success')
    return redirect(url_for('identities.settings'))

  elif 'name' in request.form and profile_form.validate_on_submit:
    current_user.user.name = profile_form.name.data
    db.session.commit()
    flash('Your name has been successfully updated.', 'success')
    return redirect(url_for('identities.settings'))

  return render_template("identities/settings.html", identity=current_user,
    profile_form=profile_form, email_form=email_form,
    password_form=password_form, section='profile')


@mod.route('/me/')
@login_required
def home():
  return render_template("identities/profile.html", identity=current_user)


@mod.route('/register/restaurant/', methods=['GET', 'POST'])
def registerRestaurant():
  """
  register a user and a restaurant
  """
  form = RegisterForm()
  restaurant_form = RestaurantForm(prefix="restaurant")
  if form.validate_on_submit() and restaurant_form.validate_on_submit():
    user = _createUser(name=form.name.data, email=form.email.data,
      password=form.password.data)

    restaurant = _create_restaurant(restaurant_form.name.data, user=user,
      category_id=restaurant_form.category_id.data)
    db.session.commit()

    login_user(user.identity)

    # flash will display a message to the user
    flash('Thanks for registering', 'success')
    # redirect user to the settings of the new created restaurant
    return redirect(url_for('restaurants.settings', id=restaurant.id))
  return render_template("identities/register_restaurant.html", form=form,
    restaurant_form=restaurant_form)

def _createUser(name, email, password):
    # create an user instance not yet stored in the database
    email = email.lower()
    identity = Identity(email=email, password=generate_password_hash(password))
    db.session.add(identity)

    user = User(name=name, identity=identity)
    # Insert the record in our database and commit it
    db.session.add(user)
    return user

@mod.route('/register/', methods=['GET', 'POST'])
def register():
  """
  Registration Form
  """
  form = RegisterForm()
  if form.validate_on_submit():
    user = _createUser(name=form.name.data, email=form.email.data, \
      password=form.password.data)

    db.session.commit()

    login_user(user.identity)

    # flash will display a message to the user
    flash('Thanks for registering', 'success')
    # redirect user to the 'home' method of the user module.
    return redirect(url_for('identities.home'))
  return render_template("identities/register.html", form=form)

@mod.route('/logout/', methods=['GET'])
@login_required
def logout():
  """
  Logout current user
  """
  logout_user()
  return redirect(url_for('identities.login'))


@mod.route('/login/', methods=['GET', 'POST'])
def login():
  """
  Login form
  """
  form = LoginForm()
  # make sure data are valid, but doesn't validate password is right
  if form.validate_on_submit():
    identity = Identity.query.filter_by(email=form.email.data).first()
    # we use werzeug to validate user's password
    if identity and check_password_hash(identity.password, form.password.data):
      if login_user(identity, remember=form.remember.data):
        return redirect(request.args.get("next") or url_for('identities.home'))
    flash('Wrong email or password', 'error')
  return render_template("identities/login.html", form=form)

app/recipes/views.py
from flask import Blueprint, render_template, flash, redirect, url_for, \
  request, Markup
from flask.ext.login import fresh_login_required

from app import db
from app.lib.decorators import remote

from app.identities.decorators import admin_required
from .models import Recipe, Ingredient, IngredientCategory, Tag
from .constants import SUGGESTION, VALID
from .forms import IngredientCategoryForm, IngredientForm, FullIngredientForm,\
  RecipeForm, FullRecipeForm, SubstituteIngredientForm, FilterForm, \
  SubstituteRecipeForm, TagForm

mod = Blueprint('recipes', __name__, url_prefix='/recipes')


@mod.route('/ingredient/edit/<int:id>/', methods=['GET', 'POST'])
@mod.route('/ingredient/edit/<int:id>/<int:page>/', methods=['GET', 'POST'])
@fresh_login_required
@admin_required
def edit_ingredient(id, page=1):
  ingredient = Ingredient.query.get_or_404(id)

  form = FullIngredientForm(obj=ingredient)
  if form.validate_on_submit():
    ingredient.name = form.name.data
    # prevent infinite recursive relation like x -> y -> z -> x -> y -> z...
    # by removing parent being child of the current ingredient
    ingredient.parents = [p for p in form.parents.data if ingredient not in p]
    ingredient.categories = form.categories.data
    ingredient.status_id = form.status_id.data
    db.session.commit()
    flash('Ingredient successfully updated', 'success')
    return redirect(url_for('recipes.ingredients'))

  kwargs = {
    "form": form,
    "ingredient": ingredient,
    "recipes": ingredient.recipes.order_by('name'),
    "ingredients": ingredient.children.order_by('name').paginate(page),
  }

  if ingredient.status_id == SUGGESTION:
    kwargs['substitute_form'] = SubstituteIngredientForm()

  return render_template("recipes/edit_ingredient.html", **kwargs)


@mod.route('/tag/<int:id>/delete/', methods=['POST'])
@fresh_login_required
@admin_required
def delete_tag(id):
  tag = Tag.query.get_or_404(id)
  db.session.delete(tag)
  db.session.commit()
  flash("Tag %s deleted." % tag.name, 'success')
  return redirect(url_for('recipes.tags'))


@mod.route('/ingredient/<int:id>/delete/', methods=['POST'])
@fresh_login_required
@admin_required
def delete_ingredient(id):
  ingredient = Ingredient.query.get_or_404(id)
  db.session.delete(ingredient)
  db.session.commit()
  flash("Ingredient %s deleted." % ingredient.name, 'success')
  return redirect(url_for('recipes.ingredients'))


@mod.route('/recipe/<int:id>/substitute/',  methods=['POST'])
@fresh_login_required
@admin_required
def recipe_substitute(id):
  recipe = Recipe.query.get_or_404(id)
  form = SubstituteRecipeForm()
  if form.validate_on_submit():
    substitute = form.recipe.data
    for dish in recipe.dishes:
      if dish.recipe_id != substitute.id:
        dish.recipe = substitute
    db.session.delete(recipe)
    db.session.commit()
    flash(
      Markup('Recipe <strong>%s</strong> substituted by <strong>%s</strong>')\
      % (recipe.name, substitute.name), 'success')
    return redirect(url_for('recipes.edit_recipe', id=substitute.id))
  return redirect(url_for('recipes.edit_recipe', id=recipe.id))


@mod.route('/ingredient/<int:id>/substitute/', methods=['POST'])
@fresh_login_required
@admin_required
def ingredient_substitute(id):
  ingredient = Ingredient.query.get_or_404(id)
  form = SubstituteIngredientForm()
  if form.validate_on_submit():
    substitute = form.ingredient.data
    for recipe in ingredient.recipes:
      if substitute not in recipe.ingredients:
        recipe.ingredients.append(substitute)
    for dish in ingredient.dishes:
      if substitute not in dish.ingredients:
        dish.ingredients.append(substitute)
    db.session.delete(ingredient)
    db.session.commit()
    flash(
      Markup('Ingredient <strong>%s</strong> substituted by <strong>%s</strong>')\
      % (ingredient.name, substitute.name), 'success')
    return redirect(url_for('recipes.edit_ingredient', id=substitute.id))
  return redirect(url_for('recipes.edit_ingredient', id=ingredient.id))


@mod.route('/ingredient/suggestions/', methods=['GET', 'POST'])
@mod.route('/ingredient/suggestions/<int:page>/', methods=['GET', 'POST'])
@fresh_login_required
@admin_required
def ingredient_suggestions(page=1):
  return render_template("recipes/ingredient_suggestions.html",
    ingredients=Ingredient.query.filter_by(status_id=SUGGESTION).\
      order_by('name').paginate(page))


@mod.route('/ingredients/', methods=['GET', 'POST'])
@mod.route('/ingredients/<int:page>/', methods=['GET', 'POST'])
@fresh_login_required
@admin_required
def ingredients(page=1):
  form = IngredientForm()
  if form.validate_on_submit():
    ingredient = Ingredient()
    ingredient.name = form.name.data
    db.session.add(ingredient)
    db.session.commit()
    flash('Ingredient successfully created', 'success')
    return redirect(url_for('recipes.edit_ingredient', id=ingredient.id))

  args = [Ingredient.status_id == VALID]

  filter_form = FilterForm(request.args, prefix='filter', csrf_enabled=False)
  if filter_form.validate() and filter_form.name.data:
    args.append(Ingredient.name.like('%%%s%%' % filter_form.name.data))

  return render_template("recipes/ingredients.html", form=form,
    filter_form=filter_form,
    ingredients=Ingredient.query.filter(*args).order_by('name').paginate(page))


@mod.route('/category/edit/<int:id>/', methods=['GET', 'POST'])
@mod.route('/category/edit/<int:id>/<int:page>/', methods=['GET', 'POST'])
@fresh_login_required
@admin_required
def edit_category(id, page=1):
  category = IngredientCategory.query.get_or_404(id)
  form = IngredientCategoryForm(obj=category)
  if form.validate_on_submit():
    category.name = form.name.data
    db.session.commit()
    flash('Category successfully updated', 'success')
    return redirect(url_for('recipes.categories'))

  return render_template("recipes/edit_category.html", form=form,
    ingredients=category.ingredients.order_by('name').paginate(page),
    category=category)


@mod.route('/categories/', methods=['GET', 'POST'])
@mod.route('/categories/<int:page>/', methods=['GET', 'POST'])
@fresh_login_required
@admin_required
def categories(page=1):
  form = IngredientCategoryForm()
  if form.validate_on_submit():
    category = IngredientCategory()
    category.name = form.name.data
    db.session.add(category)
    db.session.commit()
    flash('Category successfully created', 'success')
    return redirect(url_for('recipes.categories'))

  args = []
  filter_form = FilterForm(request.args, prefix='filter', csrf_enabled=False)
  if filter_form.validate() and filter_form.name.data:
    args.append(IngredientCategory.name.like('%%%s%%' % filter_form.name.data))

  return render_template("recipes/categories.html", form=form,
    categories=IngredientCategory.query.filter(*args).\
      order_by('name').paginate(page), filter_form=filter_form)


@mod.route('/tag/edit/<int:id>/', methods=['GET', 'POST'])
@mod.route('/tag/edit/<int:id>/<int:page>/', methods=['GET', 'POST'])
@fresh_login_required
@admin_required
def edit_tag(id, page=1):
  tag = Tag.query.get_or_404(id)
  form = TagForm(obj=tag)
  if form.validate_on_submit():
    tag.name = form.name.data
    db.session.commit()
    flash('Tag successfully updated', 'success')
    return redirect(url_for('recipes.tags'))

  return render_template("recipes/edit_tag.html", form=form,
    recipes=tag.recipes.order_by('name').paginate(page),
    tag=tag)


@mod.route('/tags/', methods=['GET', 'POST'])
@mod.route('/tags/<int:page>/', methods=['GET', 'POST'])
@fresh_login_required
@admin_required
def tags(page=1):
  form = TagForm()
  if form.validate_on_submit():
    tag = Tag(name=form.name.data)
    db.session.add(tag)
    db.session.commit()
    flash('Tag successfully created', 'success')
    return redirect(url_for('recipes.tags'))

  args = []
  filter_form = FilterForm(request.args, prefix='filter', csrf_enabled=False)
  if filter_form.validate() and filter_form.name.data:
    args.append(Tag.name.like('%%%s%%' % filter_form.name.data))

  return render_template("recipes/tags.html", form=form,
    tags=Tag.query.filter(*args).order_by('name').paginate(page),
    filter_form=filter_form)


@mod.route('/recipes/suggestions/', methods=['GET', 'POST'])
@mod.route('/recipes/suggestions/<int:page>/', methods=['GET', 'POST'])
@fresh_login_required
@admin_required
def recipe_suggestions(page=1):
  return render_template("recipes/recipe_suggestions.html",
    recipes=Recipe.query.filter_by(status_id=SUGGESTION).\
      order_by('name').paginate(page))


@mod.route('/recipes/', methods=['GET', 'POST'])
@mod.route('/recipes/<int:page>/', methods=['GET', 'POST'])
@fresh_login_required
@admin_required
def recipes(page=1):
  form = RecipeForm()
  if form.validate_on_submit():
    recipe = Recipe()
    recipe.name = form.name.data
    db.session.add(recipe)
    db.session.commit()
    flash('Recipe successfully created', 'success')
    return redirect(url_for('recipes.edit_recipe', id=recipe.id))

  args = [Recipe.status_id == 1]
  filter_form = FilterForm(request.args, prefix='filter', csrf_enabled=False)
  if filter_form.validate() and filter_form.name.data:
    args.append(Recipe.name.like('%%%s%%' % filter_form.name.data))

  return render_template("recipes/recipes.html", form=form,
    filter_form=filter_form,
    recipes=Recipe.query.filter(*args).order_by('name').paginate(page))


def suggested_ingredient(name):
  """
  get or create the ingredient
  """
  name = name.lower().strip()
  ingredient_form = IngredientForm(csrf_enabled=False, name=name)
  if ingredient_form.validate():
    # first try to find the ingredient
    ingredient = Ingredient.query.filter_by(name=name).first()
    if ingredient:
      return ingredient

    ingredient = Ingredient(name=name)
    ingredient.status_id = SUGGESTION
    return ingredient


def suggested_recipe(name, **kwargs):
  name = name.lower().strip()
  recipe_form = FullRecipeForm(csrf_enabled=False, name=name,

app/templates/admin_menu.html
<li class="divider"></li>
<li>
  <a href="{{ url_for('recipes.categories') }}">
    Categories
  </a>
</li>
<li>
  <a href="{{ url_for('recipes.recipes') }}">
    Recipes
  </a>
</li>
<li>
  <a href="{{ url_for('recipes.ingredients') }}">
    Ingredients
  </a>
</li>

app/templates/base.html
<!DOCTYPE HTML>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{url_for('static', filename="assets/favicon.ico")}}" type="image/x-icon" />
    <title>{% block title %}My Site{% endblock %}</title>
    <script>
    (function(i,g,b){"undefined"!=typeof b.module&&b.module.exports?b.module.exports=g():"undefined"!=typeof b.define&&"function"==b.define&&b.define.amd?define(i,g):b[i]=g()})("$script",function(){function i(b,a){for(var c=0,f=b.length;c<f;++c)if(!a(b[c]))return j;return 1}function g(b,a){i(b,function(c){return!a(c)})}function b(h,a,c){function f(a){return a.call?a():l[a]}function d(){if(!--j){l[e]=1;r&&r();for(var a in k)i(a.split("|"),f)&&!g(k[a],f)&&(k[a]=[])}}var h=h[m]?h:[h],n=a&&a.call,r=n?a:c,
    e=n?h.join(""):a,j=h.length;setTimeout(function(){g(h,function(a){if(p[a])return 2==p[a]&&d();p[a]=1;s(!v.test(a)&&q?q+a+".js":a,d)})},0);return b}function s(b,a){var c=d.createElement("script"),f=j;c.onload=c.onerror=c[t]=function(){c[e]&&!/^c|loade/.test(c[e])||f||(c.onload=c[t]=null,f=1,p[b]=2,a())};c.async=1;c.src=b;u.insertBefore(c,u.firstChild)}var d=document,u=d.getElementsByTagName("head")[0],v=/^https?:\/\//,l={},k={},q,p={},j=!1,m="push",e="readyState",t="onreadystatechange";!d[e]&&d.addEventListener&&
    (d.addEventListener("DOMContentLoaded",function a(){d.removeEventListener("DOMContentLoaded",a,j);d[e]="complete"},j),d[e]="loading");b.get=s;b.order=function(a,c,f){(function n(d){d=a.shift();a.length?b(d,n):b(d,c,f)})()};b.path=function(a){q=a};b.ready=function(a,c,d){var a=a[m]?a:[a],e=[];!g(a,function(a){l[a]||e[m](a)})&&i(a,function(a){return l[a]})?c():(a=a.join("|"),k[a]=k[a]||[],k[a][m](c),d&&d(e),!0);return b};return b},this);
    var CA = {};
    </script>
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
      <script>
        $script('{{url_for('static', filename="lib/jquery/jquery-1.8.2.js")}}',
          'jquery', function(){
            $script('{{url_for('static', filename="lib/bootstrap/js/bootstrap.js")}}',
              'bootstrap');
          }
        );
        $script.ready('jquery', function(){
          {% block jquery %}{% endblock %}
        });
        $script.ready('bootstrap', function(){
          {% block bootstrap %}{% endblock %}
        });
      {% block headscript %}{% endblock %}
      </script>
    {% block css %}
      <link rel="stylesheet" href="{{url_for("static",
        filename="css/main.css") }}">
      <link rel="stylesheet" href="{{url_for("static",
        filename="lib/bootstrap/css/bootstrap.css") }}">
      <link rel="stylesheet" href="{{url_for("static",
        filename="lib/bootstrap/css/bootstrap-responsive.css") }}">
    {% endblock %}
  </head>
  <body>
    <div class="navbar">
      <div class="navbar-inner">
        {% if not current_user.is_authenticated() and
          request.path != url_for('identities.login') %}
          <a class="btn btn-primary pull-right visible-phone"
            href="{{ url_for('identities.login') }}">
            login
          </a>
        {% elif current_user.is_authenticated() %}
          {% include "menu.html" %}
        {% endif %}
        <a class="brand" href="#">Chomp Around</a>
        <ul class="nav hidden-phone">
          <li><a href="/">Home</a></li>
        </ul>
        {% if not current_user.is_authenticated() and login_form and
          request.path != url_for('identities.login') %}
          <form class="navbar-form pull-right form-inline hidden-phone" method="post"
                action="{{ url_for('identities.login') }}?next={{ request.path }}">
            {{ login_form.csrf_token }}
            {{ login_form.email(class="input-small", placeholder="Email") }}
            {{ login_form.password(class="input-small", placeholder="Password") }}
            <div class="btn-group">
              <button type="submit" class="btn btn-success">Login</button>
              <button class="btn dropdown-toggle btn-success" data-toggle="dropdown">
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu pull-right">
                <li>
                  <a href="{{ url_for('identities.register') }}?next={{ request.path }}">
                    New user
                  </a>
                <li>
                <li>
                  <a href="{{ url_for('identities.registerRestaurant') }}?next={{ (request.path) }}">
                    Register your restaurant
                  </a>
                <li>
              </ul>
            </div>
          </form>
        {% endif %}
        </ul>
      </div>
    </div>
    {% for category, msg in get_flashed_messages(with_categories=true) %}
    <div class="container">
      <div class="alert alert-{{ category }}">
        <button type="button" class="close" data-dismiss="alert">x</button>
        {{ msg }}
      </div>
    </div>
    {% endfor %}
    <div class="container" id="content">{% block content %}{% endblock%}</div>
    <footer>
      <div class="container">
        <div class="row">
          <div class="span4">
            <h4>Follow</h4>
            <ul>
              <li>
                <a href="#">
                  Twitter
                </a>
              </li>
              <li>
                <a href="#">
                  Facebook
                </a>
              </li>
              <li>
                <a href="#">
                  Linkedin
                </a>
              </li>
            </ul>
          </div>
          <div class="span4">
            <h4>Contact</h4>
            <ul>
              <li>
                support:
                <a href="#">
                  support@chomparound.com
                </a>
              </li>
              <li>
                advertising:
                <a href="#">
                  advertising@chomparound.com
                </a>
              </li>
              <li>
                partnership:
                <a href="#">
                  partnership@chomparound.com
                </a>
              </li>
            </ul>
          </div>
          <div class="span4">
            <h4>About</h4>
            <ul>
              <li>
                <a href="#">
                  Team
                </a>
              </li>
              <li>
                <a href="#">
                  Upcomming
                </a>
              </li>
              <li>
                <a href="#">
                  Our Blog
                </a>
              </li>
            </ul>
          </div>
        </div>
        {% block footer %}
        {% endblock%}
      </div>
    </footer>
  </body>
  <script>{% block footerscript %}{% endblock %}</script>
</html>

app/templates/menu.html
<ul class="nav pull-right">
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      {{ current_user.user.name }} <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
      <li>
        <a href="{{ url_for('identities.home') }}">
          <i class="icon-home"></i> Profile
        </a>
      </li>
      <li>
        <a href="{{ url_for('identities.settings') }}">
          <i class="icon-edit"></i> Settings
        </a>
      </li>
      {% if current_user.is_admin() %}
        {% include "admin_menu.html" %}
      {% endif %}
      <li class="divider"></li>
      <li>
        <a href="{{ url_for('identities.logout') }}">
          <i class="icon-off"></i> Logout
        </a>
      </li>
    </ul>
  </li>
</ul>

app/templates/minimal.html
<!DOCTYPE HTML>
<html>
  <head>
    <title>{{ title }}</title>
    {% if script %}
    <script>
      {{ script|safe }}
    </script>
    {% endif %}
  </head>
  <body>
  {% if content %}{{content}}{% endif %}
  </body>
</html>